### ISSUE TITLE
DK matching only supported for package with the correct name?

### ISSUE THREAD

**Issue by mh-** [kbobrowski/en-i13n#1]
Hi @kbobrowski,

Did you also experience that submitting a "de.rki.coronawarnapp" Diagnosis Key file from an app called "de.rki.coronawarnapp.dev" doesn't work?
```
07-05 13:48:55.416  2519 10796 I ExposureNotification: Found flag-defined keys de.rki.coronawarnapp.dev:262-v1,MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE3BYTxr2HuJYQG+d7Ezu6KS8GEbFkiEvyJFg0j+C839gTjT6j7Ho0EXXZ/a07ZfvKcC2cmc1SunsrqU9Jov1J5Q== for package de.rki.coronawarnapp.dev [CONTEXT service_id=236 ]
07-05 13:48:55.442  2519 10796 W ExposureNotification: The necessary signatures did not verify [CONTEXT service_id=236 ]
```

Thanks
Michael

**Comment by kbobrowski** [comment]
Hi Michael, thanks for the info, I get `ApiException 10: Unable to validate key file signature: signature does not match` when fetching Diagnosis Keys (popup in the app). This is in case of using `de.rki.coronawarnapp.dev`. When running as `de.rki.coronawarnapp` Diagnosis Keys seem to be provided successfully, but then there is another signature check in GMS which seems to be failing:

`W ExposureNotification: Reject the api access due to the caller is not whitelisted`

Looking into it

**Comment by kbobrowski** [comment]
@mh- DKs should be now accepted even if the signature does not match, use `-f` option

https://github.com/kbobrowski/en-i13n/commit/16e35401e0545d6504cb26b376414e5534364642#diff-bb07925d937c1ca4efeb5ea521a6425aR22

**Comment by mh-** [comment]
It's getting a step further, but now:
```
07-05 20:05:36.116 28819 28913 V CachedKeyFileHolder$asyncFetchFiles: cached file:/data/user/0/de.rki.coronawarnapp.dev/cache/key-export/15ae9ad3-eca3-3bf2-ae2d-6d681501262e.zip
07-05 20:05:36.125 28819 28855 D Transaction: 75184245-1788-4d8b-aea2-dae26474cd6b - STATE CHANGE: API_SUBMISSION
07-05 20:05:36.157 28819 28819 D Transaction: Initiate Rollback
07-05 20:05:36.158 28819 28819 V RetrieveDiagnosisKeysTransaction: rollback SETUP
07-05 20:05:36.183 28819 28819 V RetrieveDiagnosisKeysTransaction: rollback TOKEN
07-05 20:05:36.197 28819 28819 V RetrieveDiagnosisKeysTransaction: rollback FILES_FROM_WEB_REQUESTS
07-05 20:05:36.224 28819 28819 W System.err: com.google.android.gms.common.api.ApiException: 39508: 
07-05 20:05:36.224 28819 28819 W System.err: 	at com.google.android.gms.common.api.internal.TaskUtil.setResultOrApiException(com.google.android.gms:play-services-base@@17.3.0:6)
07-05 20:05:36.224 28819 28819 W System.err: 	at com.google.android.gms.common.api.internal.TaskUtil.setResultOrApiException(com.google.android.gms:play-services-base@@17.3.0:2)
07-05 20:05:36.224 28819 28819 W System.err: 	at com.google.android.gms.internal.nearby.zzae.onResult(com.google.android.gms:play-services-nearby@@18.0.2-eap:2)
07-05 20:05:36.225 28819 28819 W System.err: 	at com.google.android.gms.common.api.internal.IStatusCallback$Stub.zaa(com.google.android.gms:play-services-base@@17.3.0:11)
07-05 20:05:36.225 28819 28819 W System.err: 	at com.google.android.gms.internal.base.zaa.onTransact(com.google.android.gms:play-services-base@@17.3.0:13)
07-05 20:05:36.225 28819 28819 W System.err: 	at android.os.Binder.execTransact(Binder.java:731)
07-05 20:05:36.234 28819 28913 D Transaction: null - STATE CHANGE: INIT
```

**Comment by kbobrowski** [comment]
This is most likely because quota of 20 files per day has been exceeded. You can either clean app data (which also resets the quota), or use this script to patch it in a file which counts it: https://github.com/corona-warn-app/cwa-app-android/issues/774#issuecomment-653787557

Would be nice to have an option to disable quota by patching it with frida

**Comment by mh-** [comment]
> This is most likely because quota of 20 files per day has been exceeded. You can either clean app data (which also resets the quota), or use this script to patch it in a file which counts it: [corona-warn-app/cwa-app-android#774 (comment)](https://github.com/corona-warn-app/cwa-app-android/issues/774#issuecomment-653787557)

I just deleted the app data. The script you published there would have also worked for me, with a modification, because pos=155 assumes `1: "de.rki.coronawarnapp"` and adding `".dev"` makes pos=159.

So - now it all works fine for me - you could close the issue, or keep it open as documentation for other users.

**Comment by kbobrowski** [comment]
Thanks, that sounds good :) will look into the options to automatize it, for now the information is included in README

**Comment by kbobrowski** [comment]
@mh- rate limiting can be disabled now with `-u` option

**Comment by crypt1d** [comment]
apologizes for reopening this old issue, but I cannot seem to get around the DK validation issue even when using `-k` option:

Error: 10: Unable to validate key file signature: signature does not match
Error: 10: Unable to validate key file signature: signature does not match

any thoughts on what might be the problem? This is Android 10 and Play Services v24.1.31
