### ISSUE TITLE
asyncio Threads?

### ISSUE THREAD

**Issue by mh-** [kbobrowski/en-i13n#2]
If I run `pipenv run python sign.py -p de.rki.coronawarnapp.dev -g` while this app is not yet started, the message sent in https://github.com/kbobrowski/en-i13n/blob/d78eaea70435d3641525c62343b53a1820ea10ed/signature.ts#L15 will not be received by `sign.py`.
If I add `loop.set_debug(True)` - like so:
```
    async def inject_async(self, js_file: str):
        loop = asyncio.get_running_loop()
        loop.set_debug(True)
        future = loop.create_future()
        loop.create_task(self.inject_future(js_file, future))
        return await future
```
I get this warning:
```
% pipenv run python sign.py -p de.rki.coronawarnapp.dev -g
[signature.js] injecting
Traceback (most recent call last):
  File "/Users/.../.local/share/virtualenvs/en-i13n-SQxFj8ef/lib/python3.7/site-packages/frida/core.py", line 383, in _on_message
    callback(message, data)
  File "/Users/.../en-i13n/FridaAsync.py", line 47, in callback
    future.set_result(message['payload'])
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 685, in call_soon
    self._check_thread()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 723, in _check_thread
    "Non-thread-safe operation invoked on an event loop other "
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one

```

I think there's a problem with Frida sending the message from another thread.

(For some strange reason, if the app is already running, I can extract the signature using your original script (if I do not enable asyncio debug mode).)

**Comment by kbobrowski** [comment]
Thanks for the info, cannot reproduce it on my end, perhaps `asyncio` is not the best choice here. It was convenient for fast development but perhaps just relying on callbacks would be more robust here

**Comment by kbobrowski** [comment]
@mh- it may be because the script is injected too soon after the app is launched, generally frida does not like it, there might be some issue which may block asyncio loop. Added 2 seconds delay after app launch in recent commit: https://github.com/kbobrowski/en-i13n/commit/f908b7d7a6a3187c855a0a557a149c786dd82a9a , would be great if you could check if the error still persist, and if so how long the delay should be

**Comment by mh-** [comment]
Yes, this solves the problems on my setup.
`await asyncio.sleep(1)` would not be sufficient on my setup, so 2 seconds seems to be a good value so far.

**Comment by kbobrowski** [comment]
Thanks for the input :) decreased it to 1 since it makes auto-signing more robust, let me know if there are any problems with this value, more stable mechanism of reading signature and providing it to GMS should be possible

**Comment by mh-** [comment]
Well, it's still the same issue with 1:
```
pipenv run python sign.py -p de.rki.coronawarnapp -g
[signature.js] injecting
```
... and nothing more. But I can change it locally to 2, of course ;)

**Comment by kbobrowski** [comment]
ah sorry I read your previous comment too fast, will make it configurable and set default to 2

**Comment by kbobrowski** [comment]
Kept the delay equal to 1 by default, since 2 breaks it on my setup, and it even works with 0 delay for me. But you can set custom delay now, so simply executing with `-d 2` should do the job :)

**Comment by kbobrowski** [comment]
@mh- asyncio is removed completely since it was causing more problems than it was solving. `-s` option is mandatory right now, please check README for the new process - in the end only GMS needs to be patched, which has nothing to do with the app running or not

**Comment by mh-** [comment]
> which has nothing to do with the app running or not

Just for the `get-signature` step it needs to be running, so this text 

Assign chosen package name (e.g. de.rki.coronawarnapp.dev) to your custom app (note: your app should include implementation "commons-codec:commons-codec:1.13" in build.gradle) and execute:

should read

Assign chosen package name (e.g. de.rki.coronawarnapp.dev) to your custom app (note: your app should include implementation "commons-codec:commons-codec:1.13" in build.gradle)_, run the custom app on the device_, and execute:

**Comment by kbobrowski** [comment]
thanks, fixed it
